### ISSUE TITLE
queryOBD received byte id doesn't always match sent

### ISSUE THREAD

**Issue by dcm684** [franksmicro/Arduino#1]
Using the provided OBDMPG, I noticed that I was receiving speed data as maf data. What I saw was that the PID for the received data did not match the PID for the requested data. Adding a check to see if the PIDs matched fixed the problem. 

This was my fix.

```
rxSuccess = receiveCANMessage(&msg,1000);
if (rxSuccess) {
     //Check if the PIDs match
    while(msg.data[2] != code){
        rxSuccess = receiveCANMessage(&msg,1000);
        noMatch++;
        if (noMatch >= 5) {
            return 0;
        }
    }
} else {
    return 0;
}
```

What it does is check if data was received and if the PID matches. If not try again and see if it matches. Repeat 5 times before giving up. If it timesout once, give up.

**Comment by franksmicro** [comment]
Interesting.  It would appear that the OBD is returning speed data without being asked.  Maybe when requesting speed data the first time, it returns the response more than once.  Or maybe it regularly sends speed data wihout being asked.  You don't have any other OBD devices (such as add-on instruments) that would be requesting OBD data, do you?

You could try receiving without sending and seeing if you regularly get speed data and perhaps other data back (if you are curious as to the cause).  Regardless, it is probably best to check that the received PID matches.  Congratulations on fixing the code to do this.  I will test the changes in my car over the next week or so and then add in your changes on github.

Thanks,
Frank

**Comment by dcm684** [comment]
I saw that you added the check for the PID. In my testing I noticed that my change is not completely optimal. If a bad PID is received and then no data is received, it is possible that the system will have to wait for 5 timeout periods. As a result I put in an extra case to handle a timeout.

```
noMatch++;
//Change made below
if ((noMatch >= 5) || (rxSuccess = false))
{
    return 0;
}
```

**Comment by franksmicro** [comment]
Thanks.  I will change it to:

```
    noMatch++;
    if (!rxSuccess || noMatch >= 5)
    {
        return 0;
    }
```

Do you want me to put credit to  "dcm684" in the code for these two changes?

Frank

**Comment by dcm684** [comment]
Frank, that would be great if you attribute those changes to dcm684.
