### ISSUE TITLE
Send Extended IDs Not Correct

### ISSUE THREAD

**Issue by hooovahh** [franksmicro/Arduino#2]
Sorry if this is an issue on my side, but in my testing whenever I would have the library send out an extended message, the ID that it would send out would not be correct.  

If I sent 0x123 and have isExtendedAdrs set to LOW, it would send out 0x123. (as expected)
If I sent 0x123 and have isExtendedAdrs set to HIGH it would send out 0x48C0123.
If I sent 0xFFFFAB and have isExtendedAdrs set to HIGH it would send out 0x1EACFFAB.

I've tested this using a NI USB CAN device, and a neoVI Fire.

Receiving extended messages seems to work fine.

EDIT:  The first issue I see with this is that register TXB0SIDL is leaving the extended ID bit 17, and bit 16 zero, even if the extended ID uses these bits.  This is a bug, but even zeroing these out (which they will be right now) still sends a ID that is not correct.

**Comment by hooovahh** [comment]
I believe this will fix this bug, replace the existing transmitCANMessage with this one.

boolean MCP2515::transmitCANMessage(CANMSG msg, unsigned long timeout)
{
  unsigned long startTime, endTime;
  boolean sentMessage;
  unsigned short val;
  int i;

  startTime = millis();
  endTime = startTime + timeout;
  sentMessage = false;
  if(!msg.isExtendedAdrs)
  {
    //Write standard ID registers
    val = msg.adrsValue >> 3;
    writeReg(TXB0SIDH,val);
    val = msg.adrsValue << 5;
    writeReg(TXB0SIDL,val);
  }
  else
  {
    //Write extended ID registers, which use the standard ID registers
    val = msg.extendedAdrsValue >> 21;
    writeReg(TXB0SIDH,val);
    val = msg.extendedAdrsValue >> 16;
    val = val & 0b00000011;
    val = val | (msg.extendedAdrsValue >> 13 & 0b11100000);
    val |= 1 << EXIDE;
    writeReg(TXB0SIDL,val);
    val = msg.extendedAdrsValue >> 8;
    writeReg(TXB0EID8,val);
    val = msg.extendedAdrsValue;
    writeReg(TXB0EID0,val);
  }

  val = msg.dataLength & 0x0f;
  if(msg.rtr)
    bitWrite(val,TXRTR,1);
  writeReg(TXB0DLC,val);

  //Message bytes
  digitalWrite(SLAVESELECT,LOW);
  SPI.transfer(WRITE); 
  SPI.transfer(TXB0D0);
  for(i = 0; i < msg.dataLength; i++)
    SPI.transfer(msg.data[i]);
  digitalWrite(SLAVESELECT,HIGH);

  //Transmit the message
  writeRegBit(TXB0CTRL,TXREQ,1);

  sentMessage = false;
  while(millis() < endTime)
  {
    val = readReg(CANINTF);
    if(bitRead(val,TX0IF) == 1)
    {
      sentMessage = true;
      break;
    }
  }

  //Abort the send if failed
  writeRegBit(TXB0CTRL,TXREQ,0);

  //And clear write interrupt
  writeRegBit(CANINTF,TX0IF,0);

  return sentMessage;

}

**Comment by franksmicro** [comment]
Thanks hooovahh, looking at the existing code I definitely see a problem with the logic for sending extended addresses.  I was never able to test extended addresses since my car does not use them.  

I'm still looking at your logic for extended addresses.  It is probably correct, but I want to refresh my memory on the CAN spec so I can understand the code since its been a year or so since I've looked at the specs.  I'll let you know later in the week once I have understand the logic and will merge your changes then if all looks good.

Frank

**Comment by hooovahh** [comment]
No problem.  To be honest I really learned alot and your code was very easy
to follow, I really appreciate the effort you put into it and putting it
out for the community.  I found several other MCP2515 libraries but had
difficulties with using them and yours was the easiest to understand and
modify.

The basic change was easy enough when you realize that the register bits
used for holding the standard ID, is the upper bits to the extended ID.  So
Standard ID uses two registers, one is 8 bits, the other register holds the
3 standard bits (making 11).  For extended ID there is two full registers
(making 16), in addition it uses the 11 bits from standard, and 2 others
from the shared register for standard.  So 16 + 11 + 2 is the 29 bits for
extended.  Your previous code would just use the two full registers
for extended, and would actually fill the standard registers, even if it
was an extended message (which is why I ended up seeing this bug because my
Arb ID was a combination of standard and extended).

I think I may modify your code some more.  I think it is unnecessary for
the struct to contain a short for a standard Arb ID, and a long for an
extended Arb ID in my opinion.  I plan on modifying the code to just use
the long for both extended and standard messages.  I will actually be
making an array of this struct with hopefully 50 or so elements so it is
critical I make the struct take up as little space as possible.

Again thank you very much.

On Tue, Sep 4, 2012 at 8:08 PM, Frank Kienast notifications@github.comwrote:

> Thanks hooovahh, looking at the existing code I definitely see a problem
> with the logic for sending extended addresses. I was never able to test
> extended addresses since my car does not use them.
> 
> I'm still looking at your logic for extended addresses. It is probably
> correct, but I want to refresh my memory on the CAN spec so I can
> understand the code since its been a year or so since I've looked at the
> specs. I'll let you know later in the week once I have understand the logic
> and will merge your changes then if all looks good.
> 
> Frank
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/franksmicro/Arduino/issues/2#issuecomment-8283490.

## 

Sincerely Brian Hoover
Website: http://www.brian-hoover.com
YouTube: http://www.youtube.com/hooovahh2
Facebook: http://www.facebook.com/hooovahh

**Comment by hooovahh** [comment]
One other thing I was thinking about.  When doing a read that reads an
extended message, I noticed some times the ID would use bits greater than
29.  So I ended up bitwise and'ing with 0b11111111111111111111111111111.
 The extra bits are probably from the register it reads but I didn't look
into it I just masked out the un-needed bits.

On Tue, Sep 4, 2012 at 8:41 PM, The Hoove hooovahh@gmail.com wrote:

> No problem.  To be honest I really learned alot and your code was very
> easy to follow, I really appreciate the effort you put into it and putting
> it out for the community.  I found several other MCP2515 libraries but had
> difficulties with using them and yours was the easiest to understand and
> modify.
> 
> The basic change was easy enough when you realize that the register bits
> used for holding the standard ID, is the upper bits to the extended ID.  So
> Standard ID uses two registers, one is 8 bits, the other register holds the
> 3 standard bits (making 11).  For extended ID there is two full registers
> (making 16), in addition it uses the 11 bits from standard, and 2 others
> from the shared register for standard.  So 16 + 11 + 2 is the 29 bits for
> extended.  Your previous code would just use the two full registers
> for extended, and would actually fill the standard registers, even if it
> was an extended message (which is why I ended up seeing this bug because my
> Arb ID was a combination of standard and extended).
> 
> I think I may modify your code some more.  I think it is unnecessary for
> the struct to contain a short for a standard Arb ID, and a long for an
> extended Arb ID in my opinion.  I plan on modifying the code to just use
> the long for both extended and standard messages.  I will actually be
> making an array of this struct with hopefully 50 or so elements so it is
> critical I make the struct take up as little space as possible.
> 
> Again thank you very much.
> 
> On Tue, Sep 4, 2012 at 8:08 PM, Frank Kienast notifications@github.comwrote:
> 
> > Thanks hooovahh, looking at the existing code I definitely see a problem
> > with the logic for sending extended addresses. I was never able to test
> > extended addresses since my car does not use them.
> > 
> > I'm still looking at your logic for extended addresses. It is probably
> > correct, but I want to refresh my memory on the CAN spec so I can
> > understand the code since its been a year or so since I've looked at the
> > specs. I'll let you know later in the week once I have understand the logic
> > and will merge your changes then if all looks good.
> > 
> > Frank
> > 
> > —
> > Reply to this email directly or view it on GitHubhttps://github.com/franksmicro/Arduino/issues/2#issuecomment-8283490.
> 
> ## 
> 
> Sincerely Brian Hoover
> Website: http://www.brian-hoover.com
> YouTube: http://www.youtube.com/hooovahh2
> Facebook: http://www.facebook.com/hooovahh

## 

Sincerely Brian Hoover
Website: http://www.brian-hoover.com
YouTube: http://www.youtube.com/hooovahh2
Facebook: http://www.facebook.com/hooovahh

**Comment by franksmicro** [comment]
Great!  If you want to fork the project I can easily merge your changes in.

Frank

**Comment by franksmicro** [comment]
Hoovahh, I looked over your code and the datasheet this morning.  Your logic looks like it is probably correct.  Unfortunately, I don't have any way to test the extended id.  Are you able to test?

I did notice that I had declared val to be unsigned short in transmitCANMessage().  The function it is calling expects a byte.  Apparently it is just using the low bits (since the same same issue would exist for regular addresses, and I know regular addresses are working).  But I went ahead and fixed this in the code as well.

If you want to clone and have me do a pull request let me know.  Otherwise I can just put your changes in and commit them.  Let me know if you have any other changes.  

Thanks,
Frank

**Comment by hooovahh** [comment]
Attached is my other updates.  You'll see the transmitCAN works as I have
posted previously. I noticed that the received needed to perform similar
operations to receive extended messages.

In addition I updated the struct to only contain address value which is a
long, instead of a long and a short for standard and extended messages.

I also added single shot transmission as an option when starting CAN.  It
is passed in as a boolean.  I believe these are all of the changes, feel
free to incorporate any and all of these into your own works.

I do have the ability to test these things but not here, I do this sort of
thing for work.  I didn't do extensive testing but I did send several
extended, and standard messages, as well as read them and it seems to work.
 I did not test the single shot transmission but it should just be one bit
that works the way you had it coded if it is false.

On Sat, Sep 8, 2012 at 10:04 AM, Frank Kienast notifications@github.comwrote:

> Hoovahh, I looked over your code and the datasheet this morning. Your
> logic looks like it is probably correct. Unfortunately, I don't have any
> way to test the extended id. Are you able to test?
> 
> I did notice that I had declared val to be unsigned short in
> transmitCANMessage(). The function it is calling expects a byte. Apparently
> it is just using the low bits (since the same same issue would exist for
> regular addresses, and I know regular addresses are working). But I went
> ahead and fixed this in the code as well.
> 
> If you want to clone and have me do a pull request let me know. Otherwise
> I can just put your changes in and commit them. Let me know if you have any
> other changes.
> 
> Thanks,
> Frank
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/franksmicro/Arduino/issues/2#issuecomment-8387876.

## 

Sincerely Brian Hoover
Website: http://www.brian-hoover.com
YouTube: http://www.youtube.com/hooovahh2
Facebook: http://www.facebook.com/hooovahh

**Comment by franksmicro** [comment]
Ok thanks Brian.  I didn't see any attachments though?  For your structure changes and single shot transmission?  I'll go ahead and make these updates to the public code once I get them.

Frank

**Comment by hooovahh** [comment]
Sorry the attachment didn't work, here it is on my site:

www.hooovahh.com/My Files/MCP2515.zip

On Sat, Sep 8, 2012 at 4:28 PM, Frank Kienast notifications@github.comwrote:

> Ok thanks Brian. I didn't see any attachments though? For your structure
> changes and single shot transmission? I'll go ahead and make these updates
> to the public code once I get them.
> 
> Frank
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/franksmicro/Arduino/issues/2#issuecomment-8397551.

## 

Sincerely Brian Hoover
Website: http://www.brian-hoover.com
YouTube: http://www.youtube.com/hooovahh2
Facebook: http://www.facebook.com/hooovahh

**Comment by franksmicro** [comment]
I have updated the github repository with you changes and a comment describing them.  Let me know if you see any issues with the push.  Otherwise, I will close this issue in a couple days.

Thanks again for your work!

Frank
