### ISSUE TITLE
Arduino 1.x compatibility

### ISSUE THREAD

**Issue by Olstyle** [franksmicro/Arduino#3]
In Arduino 1.0, the name of the main library changed. To make your libs work again(but still keep compatibility to older versions), you'd want to change 
# include "WProgram.h"

to
# if defined(ARDUINO) && ARDUINO >= 100

```
#include "Arduino.h"
```
# else

```
#include "WProgram.h"
```
# endif

I made these changes to use your MCP2515 lib and had no problem working with it afterwards.

**Comment by franksmicro** [comment]
Thanks.  I updated the file.

**Comment by Olstyle** [comment]
You only changed MCP2515.h, but MCP2515.cpp also uses the WProgramm.h inlcude. There it should be enough to just delete the line since the code already gets pulled through including the MCP2515 header file, making the second include pointless.

**Comment by franksmicro** [comment]
Thanks.  I went ahead and made this update.
